# Generated by Django 3.0.6 on 2020-05-05 12:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างขึ้น')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไข')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อบริษัท')),
                ('tax_id', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)], verbose_name='รหัสประจำตัวผู้เสียภาษี')),
                ('email', models.EmailField(max_length=254, verbose_name='อีเมล')),
                ('start_date', models.DateField(verbose_name='วันที่เริ่มติดต่อลูกค้า')),
            ],
            options={
                'verbose_name': 'ข้อมูลบริษัท',
                'verbose_name_plural': 'ข้อมูลบริษัท',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างขึ้น')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไข')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อวันหยุด')),
                ('date', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)], verbose_name='วันที่')),
                ('month', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='เดือนที่')),
            ],
            options={
                'verbose_name': 'ข้อมูลวันหยุด',
                'verbose_name_plural': 'ข้อมูลวันหยุด',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างขึ้น')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไข')),
                ('start_date', models.DateField(verbose_name='วันเริ่มต้นเรียกเก็บ')),
                ('end_date', models.DateField(verbose_name='วันสิ้นสุนเรียกเก็บ')),
                ('note', models.TextField(blank=True, verbose_name='จดบันทึก')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Company', verbose_name='ชื่อบริษัท')),
            ],
            options={
                'verbose_name': 'รายงานเรียกเก็บเงิน',
                'verbose_name_plural': 'รายงานเรียกเก็บเงิน',
            },
        ),
        migrations.CreateModel(
            name='ReportDetailStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างขึ้น')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไข')),
                ('name', models.CharField(max_length=200, verbose_name='สถานะเรียกเก็บ')),
            ],
            options={
                'verbose_name': 'สถานะเรียกเก็บเงิน',
                'verbose_name_plural': 'สถานะเรียกเก็บเงิน',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างขึ้น')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไข')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อบริการ')),
                ('detail', models.TextField(verbose_name='รายละเอียด')),
            ],
            options={
                'verbose_name': 'ข้อมูลบริการ',
                'verbose_name_plural': 'ข้อมูลบริการ',
            },
        ),
        migrations.CreateModel(
            name='ReportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างขึ้น')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไข')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ค่าบริการ')),
                ('invoice_date', models.DateField(verbose_name='วันเรียกเก็บ')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='จดบันทึก')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Report', verbose_name='รายงาน')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Service', verbose_name='บริการ')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoice.ReportDetailStatus', verbose_name='สถานะ')),
            ],
            options={
                'verbose_name': 'รายละเอียดเรียกเก็บเงิน',
                'verbose_name_plural': 'รายละเอียดเรียกเก็บเงิน',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างขึ้น')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไข')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ค่าบริการ')),
                ('date', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)], verbose_name='วันที่เรียกเก็บ')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Company', verbose_name='ชื่อบริษัท')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Service', verbose_name='ชื่อบริการ')),
            ],
            options={
                'verbose_name': 'ข้อมูลการแจ้งเตือน',
                'verbose_name_plural': 'ข้อมูลการแจ้งเตือน',
            },
        ),
    ]
